In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

In [2]:
#örenk veri
np.random.seed(42)

#sağlıklı kişiler sınıfı (0)
X_0 = np.random.normal(loc=5, scale=1, size=(9900, 10))
y_0 = np.zeros(9900)

#hasta kişiler sınıfı (1)
X_1 = np.random.normal(loc=8, scale=1, size=(100, 10))
y_1 = np.ones(100)

#sınıfları birleştir
X = np.vstack((X_0,X_1))
y = np.concatenate((y_0, y_1))

In [3]:
#verileri eğitim-test olrak bölme
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [4]:
#ağırlık vermeden model oluşturma
modelNonBalanced = LogisticRegression(max_iter=1000)

In [5]:
#balanced ile ağırlık vererek model oluşturma
modelBalanced = LogisticRegression(class_weight='balanced', max_iter=1000)

In [6]:
#ağırlıkları elle vererek model oluşturma
modelBalanced2 = LogisticRegression(class_weight={0:0.99,1:0.01} , max_iter=1000)

In [7]:
#model eğitme
modelNonBalanced.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [8]:
modelBalanced.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [9]:
modelBalanced2.fit(X_train, y_train)

LogisticRegression(class_weight={0: 0.99, 1: 0.01}, max_iter=1000)

In [10]:
#ağırlıksız modelin tahminleri
NonBalanced_pred = modelNonBalanced.predict(X_test)

In [11]:
#balanced kullanrak ağılıklandırılan modelim eğitimi
modelBalanced_pred = modelBalanced.predict(X_test)

In [12]:
#el ile ağılıklandırılan modelim eğitimi
modelBalanced2_pred = modelBalanced2.predict(X_test)

In [13]:
nf_mx_nonBlc = confusion_matrix(y_test, NonBalanced_pred)
print("Ağırlıksız tahminler")
print(nf_mx_nonBlc)

Ağırlıksız tahminler
[[1979    0]
 [   0   21]]


In [14]:
nf_mx_Blc = confusion_matrix(y_test, modelBalanced_pred)
print("Balanced ile ağırlıklandırılan tahminler")
print(nf_mx_nonBlc)

Balanced ile ağırlıklandırılan tahminler
[[1979    0]
 [   0   21]]


In [15]:
nf_mx_Blc = confusion_matrix(y_test, modelBalanced2_pred)
print("EL ile ağırlıklandırılan tahminler")
print(nf_mx_nonBlc)

EL ile ağırlıklandırılan tahminler
[[1979    0]
 [   0   21]]
